x-app_environment: &app_environment
  environment:
    # Common
    DEBUG: ${DEBUG}
    # Bitrix
    APP_PORT: ${APP_PORT}

services:
  app:
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app/src:/app/src
    build:
      context: ./app
    command: ["/start.sh"]
    <<: *app_environment
  