# Корневые неймспейсы
SOAPENV = "http://schemas.xmlsoap.org/soap/envelope/"
NS = "urn://xsd.dmdk.goznak.ru/exchange/3.0"
# Адресные неймспейсы
BATCH = "urn://xsd.dmdk.goznak.ru/batch/3.0"
BATCH_OPERATOR = "urn://xsd.dmdk.goznak.ru/batch-operator/3.0"
BYINGUP = "urn://xsd.dmdk.goznak.ru/buyingup/3.0"
CONTRACTOR = "urn://xsd.dmdk.goznak.ru/contractor/3.0"
DEAL = "urn://xsd.dmdk.goznak.ru/deal/3.0"
DOCUMENT = "urn://xsd.dmdk.goznak.ru/document/3.0"
TYPES = "urn://xsd.dmdk.goznak.ru/types/3.0"
