output=/app/logs/stunnel.log
pid=/var/run/stunnel.pid
foreground=yes
service=Stunnel
socket=l:TCP_NODELAY=1
socket=r:TCP_NODELAY=1
debug=7

# Коннект к рабочему конутру
[giisWork]
client=yes
accept=0.0.0.0:1500
connect=195.209.130.9:443
#cert=/stunnel/client.cer
#key=/var/opt/cprocsp/keys/root/le-09650.000
verify=0
