[supervisord]
nodaemon=true
user=root

[program:stunnel]
command=/opt/cprocsp/sbin/amd64/stunnel_thread /assets/stunnel.conf
autostart=true
autorestart=true

[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --reload
directory=/app
autostart=true
# autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
depends_on=stunnel
startdelay=2
